[build]
  base = "frontend"
  publish = "frontend/build"  # <-- Fixed publish path
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"  # <-- Use stable LTS version like 18 or 20

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
