[build]
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18.18.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
