[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "16.20.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
